{% set version = "2.3.0" %}
package:
  name: mkl_fft
  version: {{ version }}

source:
  url: https://github.com/IntelPython/mkl_fft/archive/{{ version }}.tar.gz
  sha256: df1909af7e2264ada95a86a55bf861c3974b8615ecfb53d41d3d2c882e8dcfde

build:
  number: 0
  ignore_run_exports:
    - blas

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - setuptools >=77
    - mkl-devel
    - cython
    - numpy
  run:
    - python
    - numpy
    - mkl-service

test:
  commands:
    - pip check
    - pytest -v --pyargs mkl_fft
  requires:
    - pip
    - pytest
    - scipy >=1.10
  imports:
    - mkl_fft
    - mkl_fft.interfaces
    - mkl_fft.interfaces.numpy_fft
    - mkl_fft.interfaces.scipy_fft

about:
  home: http://github.com/IntelPython/mkl_fft
  license: BSD-3-Clause
  license_file: LICENSE.txt
  description: Supports in-place and out-of-place, 1D and ND complex FFT on arrays of single and double precision with arbitrary memory layout, so long as array strides are multiples of its itemsize.
  summary: NumPy-based implementation of Fast Fourier Transform using Intel® oneAPI Math Kernel Library (OneMKL)

extra:
  recipe-maintainers:
    - ekomarova
    - vtavana
    - xaleryb
    - jharlow-intel
    - ndgrigorian
